NUM1 = str(input ("Любой символ: "))
print ("Результат", NUM1)
print ("Результат", NUM1,NUM1)
print ("Результат", NUM1,NUM1,NUM1)
print ("Результат", NUM1,NUM1,NUM1,NUM1)
print ("Результат", NUM1,NUM1,NUM1,NUM1,NUM1)
